jobs:
  android-compatibility:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout sources
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: zulu
        java-version: 11
    - continue-on-error: true
      name: Android Lint checks
      run: cd commonmark-android-test && ./gradlew :app:lint
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout sources
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: zulu
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      name: Build
      run: mvn -B package javadoc:javadoc
    strategy:
      matrix:
        java:
        - 11
        - 17
        - 21
  coverage:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout sources
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: zulu
        java-version: 11
    - continue-on-error: true
      name: Build with coverage
      run: mvn -B -Pcoverage clean test jacoco:report-aggregate
    - continue-on-error: true
      name: Publish coverage
      uses: codecov/codecov-action@v1
name: ci
on:
  repository_dispatch:
    types: trigger-ga___ci.yml
