jobs:
  release:
    environment: maven_central
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout sources
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up Maven Central repository
      uses: actions/setup-java@v2
      with:
        distribution: zulu
        gpg-passphrase: MAVEN_GPG_PASSPHRASE
        gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
        java-version: 11
        server-id: ossrh
        server-password: MAVEN_PASSWORD
        server-username: MAVEN_USERNAME
    - continue-on-error: true
      name: Set up Git user
      run: 'git config --global user.name "${{ secrets.GIT_USER_NAME }}"

        git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"

        '
    - continue-on-error: true
      env:
        MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
        MAVEN_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      name: Release
      run: 'mvn -B -Dusername=${{ secrets.GH_USERNAME }} -Dpassword=${{ secrets.GH_ACCESS_TOKEN
        }} release:prepare

        mvn -B release:perform

        '
name: release
on:
  repository_dispatch:
    types: trigger-ga___release.yml
